import './globals.css'
import type { Metadata } from 'next'
import { Amaranth, Paytone_One} from 'next/font/google'
import Main from './components/Main'

const font = Amaranth({
  subsets: ['latin'],
  weight: ['400','700']

})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}><Main/>{children}</body>
    </html>
  )
}
